<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

	<parent>
		<version>4.8.0-SNAPSHOT</version>
		<groupId>dk.au.ece.vdmj</groupId>
		<artifactId>uml</artifactId>
	</parent>

	<artifactId>uml-standard</artifactId>
	<packaging>jar</packaging>

	<name>UML Standard</name>
    <description>Translations between VDM++/VDMRT and PlantUML through VDMJ</description>

	<properties>
		<vdmj.precision>standard</vdmj.precision>
	</properties>

	<dependencies>
		<dependency>
			<groupId>dk.au.ece.vdmj</groupId>
			<artifactId>lsp</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>dk.au.ece.vdmj</groupId>
			<artifactId>vdmj</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<sourceDirectory>../src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>