<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <version>0.2.0</version>
    <groupId>dk.au.ece.vdmj</groupId>
    <artifactId>uml</artifactId>
    <name>UML</name>
    <description>Translations between VDM++/VDMRT and PlantUML through VDMJ</description>

    <properties>
        <vdmj.version>4.8.0</vdmj.version>
        <vdmj.snapshot>-SNAPSHOT</vdmj.snapshot>
    </properties>

    <profiles>
        <profile>
            <id>standard</id>
            <properties>
                <vdmj.precision>standard</vdmj.precision>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>dk.au.ece.vdmj</groupId>
                    <artifactId>lsp</artifactId>
                    <version>${vdmj.version}${vdmj.snapshot}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>dk.au.ece.vdmj</groupId>
                    <artifactId>vdmj</artifactId>
                    <version>${vdmj.version}${vdmj.snapshot}</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>highprecision</id>
            <properties>
                <vdmj.precision>high</vdmj.precision>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>dk.au.ece.vdmj</groupId>
                    <artifactId>lsp</artifactId>
                    <version>${vdmj.version}-P${vdmj.snapshot}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>dk.au.ece.vdmj</groupId>
                    <artifactId>vdmj</artifactId>
                    <version>${vdmj.version}-P${vdmj.snapshot}</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>


    <developers>
        <developer>
            <id>JonasLund</id>
            <name>Jonas Lund</name>
            <email>201906201@post.au.dk</email>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
        <developer>
            <id>LucasBjarkeJensen</id>
            <name>Lucas Bjarke Jensen</name>
            <email>201907355@post.au.dk</email>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>net.sourceforge.plantuml</groupId>
            <artifactId>plantuml</artifactId>
            <version>1.2022.7</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <finalName>${project.artifactId}-${project.version}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <finalName>
                                ${project.artifactId}-${project.version}
                            </finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>